-- Basic
require('core.plugins')
require('core.mapping')
require('core.colors')
require('core.config')

-- Plugins
require('plugins.lsp')
require('plugins.cmp')
require('plugins.todo')
require('plugins.mini')
require('plugins.mason')
require('plugins.crates')
require('plugins.comment')
require('plugins.neotree')
require('plugins.lualine')
require('plugins.whichkey')
require('plugins.telescope')
require('plugins.dashboard')
require('plugins.treesitter')
require('plugins.bufferline')
-- require('plugins.colorizer')
-- require('plugins.cellular')
-- require('plugins.trouble')
-- require('plugins.toggleterm')
